//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeBenefits = new HashSet<EmployeeBenefit>();
        }
    
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual ICollection<EmployeeBenefit> EmployeeBenefits { get; set; }
    }
}
